### ISSUE TITLE
custom star style

### ISSUE THREAD

**Issue by jhongyi** [bviebahn/react-native-star-rating-widget#15]
I can use "style" to set star container style,
but can support for star item style?

**Comment by bviebahn** [comment]
Hi, I'll add that later today. I'll let you know.

**Comment by jhongyi** [comment]
> Hi, I'll add that later today. I'll let you know.

Thank you so much.

**Comment by bviebahn** [comment]
@jhongyi I added a starStyle prop in version 1.0.19. Let me know if it works for you.

**Comment by jhongyi** [comment]
@bviebahn It works!! Thank you.
