### ISSUE TITLE
onChange rating will exceed maxStars

### ISSUE THREAD

**Issue by jhongyi** [bviebahn/react-native-star-rating-widget#16]
I defined maxStars: 5
but when I press the five star and return star is 6.
[
![Jun-28-2021 13-17-25](https://user-images.githubusercontent.com/9944080/123584013-3891f580-d813-11eb-8962-d4a65871a81c.gif)
](url)

**Comment by bviebahn** [comment]
Oh that obviously shouldn't happen. Thanks for reporting, I'll fix that today.

**Comment by bviebahn** [comment]
I just published version 1.0.20. Please let me know if you find anything else.

**Comment by jhongyi** [comment]
It works! Thank you.
