### ISSUE TITLE
(android) something wrong with swiper module

### ISSUE THREAD

**Issue by jhongyi** [bviebahn/react-native-star-rating-widget#17]
I use [https://github.com/leecade/react-native-swiper](url) with rating components,
but when scoll swiper change items, the newRating calculate of relX is negative number,
and always receive zero score.

![截圖 2021-06-30 14 45 37](https://user-images.githubusercontent.com/9944080/123914716-4762de80-d9b2-11eb-82cc-b7730dba82cc.png)

**Comment by bviebahn** [comment]
I'm not sure if I have time today but I'll look into it this evening or tomorrow. Or if you have already found a fix feel free to submit a PR. Thanks for reporting.

**Comment by bviebahn** [comment]
Please check version 1.0.21. I also added a prop 'enableSwiping' which you might want to set to false when using it in a horizontal scrollable container. Please test and let me know if you find anything else.

**Comment by jhongyi** [comment]
It's works!
But when Swiper with lots of items (maybe 7 - 10 items),
but it seem lag and not smoothly in android.

That is my code example：
`
<Swiper
  showsPagination={false}
  automaticallyAdjustContentInsets
  removeClippedSubviews
  onIndexChanged={handleSlideChange}
  containerStyle={style.swiperContainer}
>
  {scoreItems.map(item => (
    <View style={style.itemView}>
      <Text numberOfLines={2}>{item.product_name}</Text>
      <SwipeStarRating
        rating={score}
        enableHalfStar={false}
        onChange={handleScoreChange}
        starStyle={style.starContainer}
      />
    </View>
  ))}
</Swiper>
`

**Comment by bviebahn** [comment]
Not sure what you mean, can you take a video? Also I noticed removeClippedSubviews causes some problems on android. It seems smoother when I disable that.

**Comment by jhongyi** [comment]
> Not sure what you mean, can you take a video? Also I noticed removeClippedSubviews causes some problems on android. It seems smoother when I disable that.

Sorry, it my problem,
removeClippedSubviews surely make the issue on android.
