### ISSUE TITLE
onChange Sending same value

### ISSUE THREAD

**Issue by pradeepk7053** [bviebahn/react-native-star-rating-widget#18]
Sometimes onChange sending same value . In my case it's sending 0.5 even after sliding

 [
![Screenshot 2021-08-30 at 1 48 19 PM](https://user-images.githubusercontent.com/47030228/131308842-c8dd2b71-7deb-4f3b-a097-199aa8db79be.png)
](url)

**Comment by bviebahn** [comment]
Can you please post your code? I haven't had that problem yet.

**Comment by pradeepk7053** [comment]
ratingCompleted = rating => {
    console.log(rating)
    this.setState({
      rating: rating,
    });
  };

  


<StarRating
      starSize={RFPercentage(6)}
      style={{alignSelf: 'center'}}
      rating={this.state.rating}
      onChange={this.ratingCompleted}
      enableHalfStar={true}
      enableSwiping={true}
    />


sometimes working great , and after rendering again it sending 0.5 value only

**Comment by pradeepk7053** [comment]
Hey @bviebahn  it was issue of earlier version of package now it's working fine after updating in latest version
