### ISSUE TITLE
Set rating to empty

### ISSUE THREAD

**Issue by jeffreyvanhees** [bviebahn/react-native-star-rating-widget#19]
Great package! Idea: 

Currently it is not possible to clear the number of stars (i.e. to 0). Perhaps it is an idea that if the current rating is 1 and 1 is chosen again, the rating will become 0 :)

**Comment by bviebahn** [comment]
Hi!
By default `minRating` is set to 0.5. Have you tried setting it to 0?

Now that I think about it this prop is probably not needed since it can be easily implemented in `onChange` if needed. I think it makes sense to remove it and not have a minRating by default.
