### ISSUE TITLE
Not getting local updated state inside the onChange function.

### ISSUE THREAD

**Issue by yash-vaghela21** [bviebahn/react-native-star-rating-widget#20]
local state on the page level

`const [currentPage, setCurrentPage] = useState(0)`

When click on the Rating Icon i am calling the updateRating function

```
 <StarRating
    rating={surveyData[currentPage].rating}
    maxStars={5}
    emptyColor={'white'}
    starSize={45}
    enableHalfStar={false}
    onChange={updateRating}
/>
```

not getting updated state value inside onChange

```
 const updateRating = (value) => {
      //here i am not getting updated state value
      console.log(currentPage)
 }
```

i have tried to hit updateRating function on other button click i am able to get the updated local state value.
i am not sure why its causing.is it related to the StarRating Component?

**Comment by bviebahn** [comment]
Can you show me the part where you update currentPage? Are you sure it's updating?

**Comment by bviebahn** [comment]
Are you doing anything else with `updateRating`? Like memoizing? I can't see anything wrong with the code you have posted.
