### ISSUE TITLE
onChange crashing

### ISSUE THREAD

**Issue by sahilquo** [bviebahn/react-native-star-rating-widget#21]
I don't want to implement onChange because in my usecase user can change the value after. What should I do?

**Comment by bviebahn** [comment]
I'm not sure I understand your question. You don't want the user to be able to change the rating? Then you can use the `StarRatingDisplay` component which has no interaction functionality:
```js
import { StarRatingDisplay } from 'react-native-star-rating-widget';
```

**Comment by sahilquo** [comment]
Thanks, didn't know about that component, anyways great library.
