### ISSUE TITLE
Missing an onRatingEnd kind of function

### ISSUE THREAD

**Issue by xristeas** [bviebahn/react-native-star-rating-widget#23]
Is it possible that there will be another method for example onRatingEnd that will be fired only when the user stops pressing the stars component? Cause now if the user is swiping  the onChange method is fired up all the time.

**Comment by bviebahn** [comment]
Yes sure, I haven't needed that yet, but I can imagine it being useful. I'll also add a check so that `onChange` will only be called when the value actually changes.

**Comment by bviebahn** [comment]
I just published a new version 1.3.0 which includes `onRatingStart` and `onRatingEnd` props, as well as the fix to the `onChange` prop. Let me know if this works for you.

**Comment by xristeas** [comment]
Worked like a charm! Thanks for the very quick response and the even quicker release of the new version! Keep up the great work mate!
