### ISSUE TITLE
How to disable star rating?

### ISSUE THREAD

**Issue by darias08** [bviebahn/react-native-star-rating-widget#31]
Hi,

I am trying to disable the interaction for the star rating and I am wondering how can I disable it? It gives me an error message saying it's undefined when I press the star rating.

**Comment by bviebahn** [comment]
Can you show me what you have tried that is causing the error? There is a `StarRatingDisplay` component that you can use for that. Does that work for you?

**Comment by darias08** [comment]
Oh! I did not see that lol I was thinking there was a prop I can use to disable the interaction, but I didn't know there was a separate component to it! :joy:

Thank you for your kindness help! :)

**Comment by bviebahn** [comment]
Yes it's easy to miss at the very end of the readme. Glad to help :)
