### ISSUE TITLE
"RNSVGPath" was not found in the UIManager

### ISSUE THREAD

**Issue by lePoissonier** [bviebahn/react-native-star-rating-widget#32]
hi. apparently i've a render Error.
requireNativecomponent: "RNSVGPath" was not found in the UIManager.
i absolutely do not know how to solve it. can anyone help, i'm super new to react native.

**Comment by bviebahn** [comment]
Have you installed `react-native-svg`? If you have maybe you could try a different version as suggested here: https://github.com/software-mansion/react-native-svg/issues/834#issuecomment-1399103610

**Comment by babatundehraji** [comment]
Experiencing same in React Native Expo, any solution yet @rougeEloma  ?

**Comment by bviebahn** [comment]
I think the solution was to install `react-native-svg`. That doesn't work for you?

**Comment by babatundehraji** [comment]
No, it doesn't @bviebahn 

`{
  "name": "yunite",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@gorhom/bottom-sheet": "^4.4.5",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-clipboard/clipboard": "^1.11.2",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/slider": "4.4.2",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.17",
    "@types/react": "~18.0.27",
    "axios": "^1.4.0",
    "expo": "^48.0.0",
    "expo-build-properties": "~0.6.0",
    "expo-camera": "~13.2.1",
    "expo-checkbox": "~2.3.1",
    "expo-clipboard": "~4.1.2",
    "expo-constants": "~14.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-device": "~5.2.1",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-media-library": "~15.2.3",
    "expo-network": "~5.2.1",
    "expo-secure-store": "~12.1.1",
    "expo-sharing": "~11.2.2",
    "expo-skeleton-loader": "^1.1.3",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.4",
    "react": "18.2.0",
    "react-native": "0.71.13",
    "react-native-animatable": "^1.3.3",
    "react-native-dropdown-select-list": "^2.0.4",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-loading-spinner-overlay": "^3.0.1",
    "react-native-mime-types": "^2.4.0",
    "react-native-paper": "^5.6.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-root-toast": "^3.4.1",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-svg": "12.3.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-tab-view": "^3.5.1",
    "react-native-view-shot": "3.5.0",
    "react-native-webview": "11.26.0",
    "react-navigation-stack": "^2.10.4",
    "react-query": "^3.39.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@expo/metro-config": "^0.10.7",
    "@types/expo": "^33.0.1",
    "@types/mime": "^3.0.1",
    "@types/react": "~18.0.27",
    "metro-config": "^0.79.1",
    "react-native-dotenv": "^3.4.9",
    "typescript": "^4.9.4"
  },
  "private": true
}
`

**Comment by bviebahn** [comment]
Are you sure it's installed correctly? When you use it as described here it works? https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md#usage

**Comment by babatundehraji** [comment]
Noted. Thank you @bviebahn

**Comment by babatundehraji** [comment]
Hi @bviebahn still experiencing the issues, I shared it here: https://stackoverflow.com/questions/77258590/react-native-expo-app-crashing-on-ios-testflight-and-android-internal-testing-w

I need your help, please!

**Comment by bviebahn** [comment]
I don't see anything wrong with your code just looking at it. You can also check the example project, which is also an expo project. Maybe try to run it and see if you find any differences: https://github.com/bviebahn/react-native-star-rating-widget/tree/master/example

**Comment by babatundehraji** [comment]
Great, thank you @bviebahn 
Will look into it

**Comment by babatundehraji** [comment]
Hi @bviebahn 

Increasing the "react-native-svg": version from "13.4.0"  to "13.14.0"(Latest) works for me.

Thank you

**Comment by bviebahn** [comment]
Interesting, good to know. Thanks for the update!
