### ISSUE TITLE
enableSwiping

### ISSUE THREAD

**Issue by mertkahramanturk** [bviebahn/react-native-star-rating-widget#49]
enableSwiping props does not work. when I send it as props it doesn't work. When I checked the source codes, I saw that it was dysfunctional. Could it be because of the version?

**Comment by bviebahn** [comment]
Not sure what you mean, it seems to work for me.

**Comment by bviebahn** [comment]
Not a prop, but there is a StarRatingDisplay component that you can import for readonly functionality.
