### ISSUE TITLE
ReadOnly

### ISSUE THREAD

**Issue by felixrolando** [bviebahn/react-native-star-rating-widget#53]
Hi, Thanks for you package, but some time i need readonly

**Comment by bviebahn** [comment]
Hi,

There is a separate 'StarRatingDisplay' component for that. I will update the readme, it's only mentioned at the very end, you're not the first to miss that.

**Comment by felixrolando** [comment]
Hi, thanks so much.

**Comment by codewitharun** [comment]
I want to disable the interaction and would like to make stars readOnly, but I am unable to find that functionality, moreover without onChange it is giving error and with that it is making it clickable.

  <StarRatingDisplay
                  rating={rating}
                  starSize={22}
                  color={R.colors.buttonColor}
                  starStyle={{marginHorizontal: 0}}
                  StarRatingDisplay={false}
                  style={{
                    marginTop: 5,
                  }}
                />

Will really be helpful for any assistance

**Comment by bviebahn** [comment]
See here: https://github.com/bviebahn/react-native-star-rating-widget#non-interactive-starratingdisplay-component
Make sure you're importing the right component.
This:
```js
import { StarRatingDisplay } from 'react-native-star-rating-widget';
```
not this:
```js
import StarRatingDisplay from 'react-native-star-rating-widget';
```

**Comment by codewitharun** [comment]
thank you it worked 👍🏻

**Comment by bviebahn** [comment]
Thanks for the info, I hadn't noticed. Should be updated now.
