### ISSUE TITLE
Add emptyColor option fill the star instead of it just colors the border

### ISSUE THREAD

**Issue by kvntzn** [bviebahn/react-native-star-rating-widget#68]
Currently, the `emptyColor` only colors the border of the star. We can add a prop to use a `star type` for the `emptyColor`.

**Comment by bviebahn** [comment]
I'm not sure what you mean. The default empty icon is basically just a border, it's not filled. You can always use the StarIconComponent prop to do your own customizations. Here is an example: https://github.com/bviebahn/react-native-star-rating-widget/blob/master/example/src/CustomIconExample.tsx
