### ISSUE TITLE
Add the ability to adjust the spacings of the stars

### ISSUE THREAD

**Issue by jar145** [bviebahn/react-native-star-rating-widget#69]
It doesn't look like there is a way to adjust the spacing between the stars/icons. Maybe I'm wrong though. If not adding that customization would be amazing.

**Comment by bviebahn** [comment]
There is a `marginHorizontal: 5` on the icons, you can set your own style using the starStyle prop.

**Comment by jar145** [comment]
That worked perfectly, and was able to do negative numbers to fit my need.
