### ISSUE TITLE
Loss of precision during arithmetic conversion

### ISSUE THREAD

**Issue by jazzcheema** [bviebahn/react-native-star-rating-widget#80]
-widget does not work with floats if using latest React Native .76, eg: 2.5, 3.5  
-enableHalfStar seems to be nonfunctional 
-receive an error: Loss of precision during arithmetic conversion: (long long) X.X

**Comment by bviebahn** [comment]
Thanks for reporting, should be fixed now!

**Comment by jazzcheema** [comment]
thank you for maintaining this component! extremely stellar you were able to resolve <24 hours! thank you.

**Comment by menesyurtlu** [comment]
I faced this issue. this issue causes by enableHalfStar. If you want to use half stars, you need to changed it's type to string and the solution is just like this:

`<StarRating
                rating={this.state.rating}
                enableHalfStar={true}
                onChange={(value: number) => {
                  this.setState({rating: value.toString()});
                }}
              />`

**Comment by menesyurtlu** [comment]
Which update? I had faced it last week

**Comment by jazzcheema** [comment]
should be on: 1.9.2

just tested it again on my RN app. half star ratings are working for me. Code snippet below: 

`       <StarRating
              disable={false}
              enableHalfStar={true}
              maxStars={5}
              starSize={50}
              color="#378cff"
              emptyColor="#378cff"
              rating={starCount}
              enableSwiping={true}
              selectedStar={(rating) => handleRating(rating)}
              onChange={(newRating) => handleRating(newRating)}
              onRatingStart={handleStartRating}
              onRatingEnd={handleFinishRating}
              />`

**Comment by menesyurtlu** [comment]
I had included last week and idk why but I have 1.9.1 in my package.json. I will check it

**Comment by jazzcheema** [comment]
update should fix! good luck
